name: CI laravel

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.testing file
        run: |
          cat <<EOF > src/.env.testing
          APP_ENV=testing
          APP_DEBUG=true
          APP_KEY=base64:$(openssl rand -base64 32)

          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=test_database
          DB_USERNAME=test_password
          DB_PASSWORD=test_password

      - name: Create test mysql.env file for docker compose
        run: |
          cat <<EOF > env/mysql.env
          MYSQL_CONNECTION=mysql
          MYSQL_HOST=mysql
          MYSQL_PORT=3306
          MYSQL_DATABASE=test_database
          MYSQL_PASSWORD=test_password
          MYSQL_ROOT_PASSWORD=test_password

      - name: Build docker
        run: docker compose build --env=testing

      - name: Install composer dependencies
        run: docker compose run --rm composer install --no-dev --optimize-autoloader --env=testing

      - name: Run migrations
        run: docker compose run --rm artisan migrate --force --env=testing

      - name: Run tests
        run: docker compose run --rm artisan test --env=testing
