name: Deploy Laravel Dump project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Docker on Ubuntu
      - run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to GitHub CLI
        run: |
          echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: Connect via SSH
        run: |
          gh cs ssh --codespace ${{ secrets.CODESPACE_NAME }}

      - name: Down Docker
        run: docker-compose down

      # ! нужно только если идёт деплой на отдельную ветку
      - name: Pull commits to deploy branch
        run: | 
          git pull --all
          git checkout deploy
          git rebase master
          git push origin deploy --force

      - name: Start containers
        run: docker-compose up -d --build

      - name: Install PHP dependencies
        run: docker-compose run --rm composer install --no-dev --optimize-autoloader

      - name: Run migrations
        run: docker-compose run --rm artisan migrate --force

      - name: Cache configuration
        run: |
          docker-compose run --rm artisan config:clear
          docker-compose run --rm artisan config:cache
          docker-compose run --rm artisan route:cache
          docker-compose run --rm artisan event:cache
          docker-compose run --rm artisan view:cache

      - name: Install JS dependencies & build assets
        run: docker-compose exec php sh -c "npm i && npm run build"
